language: python

jobs:
  include:
    - name: "Python 3.7 with ubuntu 18.04 - Bionic"
      os: linux
      dist: bionic
      python: 3.7
    - name: "Python 3.8 with ubuntu 18.04 - Bionic"
      os: linux
      dist: bionic
      python: 3.8
    - name: "Python 3.9 with ubuntu 18.04 - Bionic"
      os: linux
      dist: bionic
      python: 3.9
    - name: "Python pypy3 with ubuntu 18.04 - Bionic"
      os: linux
      dist: bionic
      python: pypy3

install:
  - pip install python-dateutil
  - pip install pytz
  - pip install lxml
  - pip install aiofiles
  - pip install aiosqlite
  - pip install pytest --upgrade
  - pip install pytest-asyncio
  - pip install pytest-mock
  - pip install cryptography
  - pip install dataclasses
  - pip install --editable .
# command to run tests
script: pytest -v -s
