language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
# command to install dependencies
install:
  - pip install python-dateutil
  - pip install pytz
  - pip install lxml
  - pip install aiofiles
  - pip install aiosqlite
  - pip install pytest --upgrade
  - pip install pytest-asyncio
  - pip install cryptography
  - pip install dataclasses
# command to run tests
script: pytest -v -s
