language: python
#python:
#  - "3.6"
#  - "3.7"
#  - "3.8"
#  - "pypy3"
# command to install dependencies

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.6.11 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.11
        - python -m pip install --upgrade pip
    - name: "Python 3.7.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.8
        - python -m pip install --upgrade pip
    - name: "Python 3.8.5 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.5
        - python -m pip install --upgrade pip
install:
  - pip install python-dateutil
  - pip install pytz
  - pip install lxml
  - pip install aiofiles
  - pip install aiosqlite
  - pip install pytest --upgrade
  - pip install pytest-asyncio
  - pip install cryptography
  - pip install dataclasses
# command to run tests
script: pytest -v -s
